# Generates files and package for BIPES offline version
# use account 'github-actions[bot]' to set the git config

name: BIPES OFFLINE Package Generator

on: [push]
jobs:
  BIPES_OFFLINE:
    runs-on: ubuntu-latest
    steps:
      #- run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Remove existing toolboxT.xml file
        run: echo > ${{ github.workspace }}/ui/toolboxT.xml
      - name: Create unified toolbox file toolboxT.xml
        run: |
          for i in ${{ github.workspace }}/ui/toolbox*xml; do echo "Including file $i"; N=`echo $i | awk -F'_' '{ print $6 }' | awk -F'.' '{ print $1 }'`; echo "<XML ID=toolbox_${N}>" >> ${{ github.workspace }}/ui/toolboxT.xml; cat $i |grep -v "<document>" >> ${{ github.workspace }}/ui/toolboxT.xml; echo "</XML>" >> ${{ github.workspace }}/ui/toolboxT.xml; done          
      - run: echo "ðŸ This job's status is ${{ job.status }}."
      - name: Temporary TEST - Create/update text file
        run: date > test.txt
      - name: Create ZIP file with BIPES OFFLINE Release
        run: zip -r bipes_offline.zip *
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add test.txt
          git add ui/toolboxT.xml
          git add bipes_offline.zip
          git commit -m "BIPES OFFLINE Package generated automatically"
          git push        
